[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "pyautogui>=0.9.54",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "undetected-chromedriver>=3.5.5",
]
